### ISSUE TITLE
Second and third objectives not achieved

### ISSUE THREAD

**Issue by ftram** [ibm-cloud-docs/tutorials#43]
The tutorial lacks the parts related to the second and third objective:
- Create, deploy and bind Node.js actions in Cloud Functions
- Access a Db2 database from Cloud Functions using Node.js

**Comment by l2fprod** [comment]
@ftram can you comment on which tutorial you are looking at?

**Comment by ftram** [comment]
Yes, sorry, I forgot to mention it. I am looking at the tutorial "Build a database-driven Slackbot" (https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-slack-chatbot-database-watson), that is the file "slack-chatbot-database-watson.md" here in "ibm-cloud-docs/tutorials"

**Comment by data-henrik** [comment]
@ftram Why do you think those objectives are not met? Have you tried out the tutorial and also looked at the deployed code?

**Comment by ftram** [comment]
Yes I have tried the tutorial. I create the bot on slack and tested it as explained.
But then the tutorial does not explain how to "Create, deploy and bind Node.js actions in Cloud Functions" and "Access a Db2 database from Cloud Functions using Node.js".
Where is the "database-driven" part of the tutorial?
Regarding the code... there are many files... but the purpose of the tutorial at https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-slack-chatbot-database-watson should be the step by step guide how to build a bot on slack connected to a DB. Where is the DB part of the tutorial? This part is missing

**Comment by data-henrik** [comment]
Are you looking for specific instructions and what degree of detail? We are always interested to improve tutorials. 

The code and the executed script are documented (with comments) and a first step could be to point out that fact.

**Comment by ftram** [comment]
I am interested in learning how to make watson assistant communicate with a database, in this case, via IBM Cloud Functions. I didn't find a guide/instructions to how to achieve this. So when I found this tutorial I was confident that I had found that guide.

**Comment by data-henrik** [comment]
Did you look at the code and script comments? Could you follow them? We assume that developers take a look at the code in the provided GitHub repository.

**Comment by ftram** [comment]
Yes, there very few comments.
In README.md it is written "The tutorial with detailed **step-by-step instructions** is available at https://cloud.ibm.com/docs/tutorials?topic=solution-tutorials-slack-chatbot-database-watson#slack-chatbot-database-watson." Where are the step-by-step instructions of the database and IBM Cloud function part?
If you do not want give here explanations of how to integrate watson assistant with a DB via IBM Cloud Function, at least give some references to tutorials, examples, articles and documents where it is explained how to do it.

**Comment by data-henrik** [comment]
The tutorial itself has the steps to deploy the code. The files and their purpose are described and then linked to in the README. The comments assume basic programming experience because the solution tutorials are meant for an audience after completing the "hello world" / introductory tutorials as offered by individual services.

Writing code for Db2 is explained in the Db2 knowledge center in the following section: https://www.ibm.com/support/knowledgecenter/SSEPGG_11.5.0/com.ibm.db2.luw.container.doc/doc/t0024244.html

IBM maintains a portal with resources for developers and to get started at https://developer.ibm.com/ and https://cognitiveclass.ai/

The basics for writing Cloud Function actions are linked to from the tutorial. With that in place, the tutorial provides the steps and the code to compose a solution based on the individual parts.

Does that help?

**Comment by ftram** [comment]
Ok, I am looking at the various docs, tutorials etc Thanks for the kind replies.
However I think you could spend some more words, in the tutorial, on the parts regarding the two mentioned objectives.
Regards
